name: Build

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
      inputs:
        version:
          description: Firmware Version
          required: true
          type: string

env:
  FIRMWARE_VERSION: ${{ github.event.inputs.version }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Dependencies
        uses: ./.github/actions/setup

      - name: Get Nordic SDK
        uses: ./.github/actions/nordic

      - name: Build
        run: cd build; make -j4 release

      # - name: Archive production artifacts
      #   uses: actions/upload-artifact@v3
      #   with:
      #     path: build/release/Wireless_neuron_final.hex
