name: Build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # - name: Checkout
      #   uses: actions/checkout@v4
      #   with:
      #     fetch-depth: 1
      #     submodules: recursive

      - name: Install Pre-requisites
        run: |
          sudo apt-get update -y
          # sudo apt-get install -y software-properties-common
          # sudo add-apt-repository ppa:deadsnakes/ppa
          # sudo apt-get update -y
          # sudo apt-get remove -y python3
          sudo apt-get install -y \
            build-essential \
            wget \
            make=4.3-4.1build2 \
            python3.11 \
            gcc-arm-none-eabi
            # gcc-arm-none-eabi=10:10.3.0-1
          sudo pip install intelhex

      - name: Verify Pre-requisites
        run: |
          echo "make: $(make --version | head -n 1)"
          echo "gcc-arm-none-eabi: $(arm-none-eabi-gcc --version | head -n 1)"
          echo "python: $(python3 --version)"
          echo "intelhex: $(python3 -c 'import intelhex; print(intelhex.__version__)')"

      # - name: Setup Nordic SDK
      #   env:
      #     library_sdk_path: "libraries/SDK"
      #     nordic_sdk_path: "nRF5_SDK_17.1.0_ddde560"
      #     nordic_sdk_zip: "${nordic_sdk_path}.zip"
      #     nordic_sdk_url: "https://nsscprodmedia.blob.core.windows.net/prod/software-and-other-downloads/sdks/nrf5/binaries/nrf5_sdk_17.1.0_ddde560.zip"
      #   run: |
      #     mkdir -p ${library_sdk_path}
      #     cd ${library_sdk_path}
      #     wget -O ${nordic_sdk_zip} ${nordic_sdk_url}
      #     unzip ${nordic_sdk_zip}
      #     rm ${nordic_sdk_zip}

      # - name: Build
      #   run: |
      #     cd build
      #     make release
