name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: recursive

      - name: Install Pre-requisites
        run: |
          set -e
          sudo apt-get install -y \
            build-essential \
            wget \
            make \
            gcc-arm-none-eabi
          sudo add-apt-repository ppa:deadsnakes/ppa
          sudo apt-get update -y
          sudo apt-get install -y python3.11
          sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.11 1
          sudo update-alternatives --set python3 /usr/bin/python3.11
          sudo pip install intelhex

      - name: Verify Pre-requisites Versions
        run: |
          set -e
          echo "make: $(make --version | head -n 1)"
          echo "gcc-arm-none-eabi: $(arm-none-eabi-gcc --version | head -n 1)"
          echo "python: $(python3 --version)"

      - name: Setup Nordic SDK
        env:
          LIBRARY_SDK_PATH: libraries/SDK
          NORDIC_SDK_VERSION: 17.1.0_ddde560
          NORDIC_SDK_PATH: nRF5_SDK_${NORDIC_SDK_VERSION}
          NORDIC_SDK_ZIP: ${NORDIC_SDK_PATH}.zip
          NORDIC_SDK_URL: https://nsscprodmedia.blob.core.windows.net/prod/software-and-other-downloads/sdks/nrf5/binaries/nrf5_sdk_${NORDIC_SDK_VERSION}.zip
        run: |
          mkdir -p ${LIBRARY_SDK_PATH}
          cd ${LIBRARY_SDK_PATH}
          wget -O ${NORDIC_SDK_ZIP} ${NORDIC_SDK_URL}
          unzip ${NORDIC_SDK_ZIP}
          rm ${NORDIC_SDK_ZIP}

      - name: Build
        run: |
          cd build
          make release
