name: Build Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: recursive

      - name: Docker Build
        run: |
          docker build \
            --build-arg BUILD_TYPE=release \
            -t defy \
            .
